%YAML:1.0
camera_matrix:  !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 1431.699692,     0.     ,   929.778185,
             0.     ,  1419.990396,   519.163383,
             0.     ,     0.     ,     1.     ]

distortion_coefficients:  !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [0.028747, -0.102466, 0.000596, -0.004700, 0.000000]



